### ISSUE TITLE
ValueError when filtering list Coco2Voc

### ISSUE THREAD

**Issue by TheMinecraftOverlordYT** [nipdep/img-ann#13]
Hello,

When calling convertor.coco2voc, I get an error message regarding filterImgObj in pascalvoc.py. You are currently using this line: 
`        filtered_list = self.annotations.loc[self.annotations["image_id"] == int(img_id), :].values.tolist()`
However, this conversion to an int fails when the image_id is in the form of something like a UUID, as is the case with my dataset (here is an example of an image_id: c7bdac02-e077-11e9-9cb5-5cf370671a19)
![image](https://user-images.githubusercontent.com/14249937/124018826-4633b080-d9b6-11eb-9a52-555ab2b3cebd.png)

Is there a way to not need to cast the id to an int?

**Comment by nipdep** [comment]
I'll look into this.

**Comment by nipdep** [comment]
I curated the problem in the new release, but still library does not support `pascalVOC` file in type UUID for `image_id` or `object_id` fields. [means `voc2coco()` will not work if .xml file `image_id` field in UUID type.] 
Also, I'll look into resolve that issue too.
